# =============================================================================
# packer/linux/ubuntu.pkr.hcl
# Builds the Ubuntu 24.04 LTS k3s server VM using the Hyper-V ISO builder.
# =============================================================================

packer {
  required_version = ">= 1.10.0"
  required_plugins {
    hyperv = {
      version = ">= 1.1.3"
      source  = "github.com/hashicorp/hyperv"
    }
  }
}

# ---------------------------------------------------------------------------
# Variables (injected by Build-LinuxVM.ps1 via -var flags)
# ---------------------------------------------------------------------------
variable "vm_name" {
  type    = string
  default = "k8s-linux-master"
}
variable "cpu_count" {
  type    = number
  default = 2
}
variable "memory_mb" {
  type    = number
  default = 6144
}
variable "disk_size_mb" {
  type    = number
  default = 61440
}
variable "switch_name" {
  type    = string
  default = "k8s-external"
}
variable "admin_user" {
  type    = string
  default = "k8sadmin"
}
variable "admin_pass" {
  type      = string
  default   = "ChangeMe123!"
  sensitive = true
}
variable "iso_url" {
  type = string
}
variable "iso_checksum" {
  type = string
}
variable "output_dir" {
  type    = string
  default = "../../vhdx/linux"
}
variable "k3s_version" {
  type    = string
  default = "v1.32.5+k3s1"
}
variable "ssh_private_key_file" {
  type    = string
  default = ""
}

# ---------------------------------------------------------------------------
source "hyperv-iso" "ubuntu" {
  vm_name          = var.vm_name
  cpus             = var.cpu_count
  memory           = var.memory_mb
  disk_size        = var.disk_size_mb
  switch_name      = var.switch_name
  generation       = 2
  enable_secure_boot = false
  enable_dynamic_memory = false

  iso_url          = var.iso_url
  iso_checksum     = var.iso_checksum

  # Packer serves user-data from this directory via its built-in HTTP server
  http_directory   = "http"

  # Boot command for Ubuntu 24.04 autoinstall on Hyper-V Gen2 UEFI.
  # Drop into GRUB command shell ('c') and boot manually — more reliable than
  # navigating the menu with arrow keys which can miss the right kernel line.
  boot_wait        = "15s"
  boot_command = [
    "c<wait5>",
    "set gfxpayload=keep<enter><wait>",
    "linux /casper/vmlinuz quiet autoinstall ds=nocloud-net\\;seedfrom=http://{{.HTTPIP}}:{{.HTTPPort}}/ ---<enter><wait5>",
    "initrd /casper/initrd<enter><wait5>",
    "boot<enter><wait>"
  ]

  # SSH communicator — Packer connects after OS install completes.
  # Uses key-based auth (ephemeral keypair generated by Build-LinuxVM.ps1 and
  # injected into user-data authorized_keys) — avoids cloud-init password auth battles.
  communicator          = "ssh"
  ssh_username          = var.admin_user
  ssh_private_key_file  = var.ssh_private_key_file
  ssh_agent_auth        = false
  ssh_timeout           = "60m"
  ssh_handshake_attempts = 30

  shutdown_command = "echo '${var.admin_pass}' | sudo -S shutdown -P now"
  shutdown_timeout = "15m"

  output_directory = var.output_dir
  headless         = true
}

# ---------------------------------------------------------------------------
build {
  name    = "ubuntu-k3s-base"
  sources = ["source.hyperv-iso.ubuntu"]

  # --- 1: Base packages, kernel modules, sysctl ---
  provisioner "shell" {
    script           = "scripts/01-base.sh"
    execute_command  = "echo '${var.admin_pass}' | sudo -S bash {{.Path}}"
    expect_disconnect = true
  }

  # --- 2: Install k3s binary only (no server/agent config, no systemd unit) ---
  provisioner "shell" {
    script           = "scripts/02-install-k3s-binary.sh"
    execute_command  = "echo '${var.admin_pass}' | sudo -S bash {{.Path}}"
    environment_vars = [
      "K3S_VERSION=${var.k3s_version}"
    ]
  }

  # --- 3: cloud-init clean — wipe state so differencing clones get a fresh instance ---
  provisioner "shell" {
    script           = "scripts/03-cloud-init-clean.sh"
    execute_command  = "echo '${var.admin_pass}' | sudo -S bash {{.Path}}"
  }
}
